curricula/urls.py
# Curriculum - Web application for creating and managing educational curricula
# Copyright (C) 2010  The Ministry of Education, Science and Culture, Iceland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from curricula.forms.programmes import ProgrammeCreateForm, ProgrammeDescriptionForm, ProgrammeOrganizationForm, ProgrammeCompetenceForm, ProgrammeEvaluationForm, ProgrammeCoursesForm, ProgrammeWizard
from curricula.forms.courses import CourseCreateForm, CourseDescriptionForm, CourseGoalForm, CourseEvaluationAuthorForm, CourseWizard


urlpatterns = patterns('curricula',
#	(r'^$', 'html.index'),        
	url(r'^framhaldsskolar/afangar/minir-afangar/$', 'views.my_courses', name='my-courses'),
	url(r'^framhaldsskolar/afangar/osamthykktir-afangar/$', 'views.unapproved_courses', name='unapproved_courses'),
        url(r'^framhaldsskolar/afangar/fyrirmyndarafangar/$', 'views.list_exemplary_courses', name='list-exemplary-courses'),
	url(r'^framhaldsskolar/afangar/fyrirmyndarafangar/fyrirmyndarafangi/(?P<id>[^/]*)/$', 'views.view_exemplary_course', name='view-exemplary-course'),

	url(r'^framhaldsskolar/afangar/afangi/(?P<id>[^/]*)/$', 'views.view_course', name='view-course'),
	url(r'^framhaldsskolar/afangar/birta/(?P<id>[^/]*)/$', 'views.publish_course', name='publish-course'),
	url(r'^framhaldsskolar/afangar/eyda/(?P<id>[^/]*)/$', 'views.delete_course', name='delete-course'),
	url(r'^framhaldsskolar/afangar/samthykkja/(?P<id>[^/]*)/$', 'views.approve_course', name='approve-course'),
	url(r'^framhaldsskolar/afangar/endurvekja/(?P<id>[^/]*)/$', 'views.reactivate_course', name='reactivate-course'),

	url(r'^framhaldsskolar/afangar/nyr-afangi/$', CourseWizard([CourseCreateForm, CourseDescriptionForm, CourseGoalForm, CourseEvaluationAuthorForm])),
	url(r'^framhaldsskolar/brautir/ny-braut/$', ProgrammeWizard([ProgrammeCreateForm, ProgrammeDescriptionForm, ProgrammeOrganizationForm, ProgrammeCompetenceForm, ProgrammeEvaluationForm, ProgrammeCoursesForm])),

        url(r'^raduneytisstjornbord/stillingar-fyrir-framhaldsskola/namslokategundir/', 'views.list_professions'),
        url(r'^raduneytisstjornbord/stillingar-fyrir-framhaldsskola/proflokategundir/', 'views.list_exams'),
        url(r'^raduneytisstjornbord/stillingar-fyrir-framhaldsskola/namssvid/', 'views.list_fields'),
        url(r'^raduneytisstjornbord/stillingar-fyrir-framhaldsskola/fyrirmyndarafangar/$', 'views.list_exemplary_courses', name='adminlist-exemplary-courses'),
        url(r'^raduneytisstjornbord/stillingar-fyrir-framhaldsskola/fyrirmyndarafangar/nyr-fyrirmyndarafangi/(?P<id>[^/]*)/$', 'views.make_exemplary_course', name='make-exemplary-course'),
	
)

schools/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('schools.views',
	url(r'^$', 'schools.list_feeds'),

	url(r'^leikskolar/$', 'schools.list_feeds', kwargs={'level':'preschool'}),
	url(r'^leikskolar/skolar/allir-skolar/$', 'schools.list_schools', kwargs={'level':'preschool'}),
	url(r'^leikskolar/skolar/landssvaedi/(?P<area>[^/]*)/$', 'schools.list_schools', kwargs={'level':'preschool'}),

	url(r'^grunnskolar/$', 'schools.list_feeds', kwargs={'level':'primary'}),
	url(r'^grunnskolar/skolar/allir-skolar/$', 'schools.list_schools', kwargs={'level':'primary'}),
	url(r'^grunnskolar/skolar/landssvaedi/(?P<area>[^/]*)/$', 'schools.list_schools', kwargs={'level':'primary'}),

	url(r'^framhaldsskolar/$', 'schools.list_feeds', kwargs={'level':'secondary'}),
        url(r'^framhaldsskolar/skolar/allir-skolar/$', 'schools.list_schools', kwargs={'level':'secondary'}),
	url(r'^framhaldsskolar/skolar/landssvaedi/(?P<area>[^/]*)/$', 'schools.list_schools', kwargs={'level':'secondary'}),

	url(r'^skoli/(?P<school>[^/]*)/$', 'schools.school_info', name='school-info'),
)

urlpatterns += patterns('country.views',
        url(r'^leikskolar/skolar/landssvaedi/$', 'regions.list_areas', kwargs={'color':settings.PRESCHOOL_COLOR}),
        url(r'^grunnskolar/skolar/landssvaedi/$', 'regions.list_areas', kwargs={'color':settings.PRIMARY_SCHOOL_COLOR}),
        url(r'^framhaldsskolar/skolar/landssvaedi/$', 'regions.list_areas', kwargs={'color':settings.SECONDARY_SCHOOL_COLOR}),
)

curricula/models/courses.py
#! -*- encoding: utf-8 -*-

# Curriculum - Web application for creating and managing educational curricula
# Copyright (C) 2010  The Ministry of Education, Science and Culture, Iceland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

import uuid

class Subject(models.Model):
	name = models.CharField(max_length=128)
	author = models.ForeignKey(User, editable=False)

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.lower()
		super(Subject, self).save(*args,**kwargs)
    
	class Meta:
		app_label = 'curricula'
		verbose_name = _('subject')
		verbose_name_plural = _('subjects')

class SubjectCombination(models.Model):
	combination = models.ManyToManyField(Subject)
	abbreviation = models.CharField(max_length=4)
	author = models.ForeignKey(User, editable=False)
	
	def __unicode__(self):
		return "%s - %s" % (self.abbreviation, self.subjects())

	# Returns an array of subjects belonging to this combination
	def subjects_list(self):
		return [x.name for x in self.combination.all()]

	# Returns a comma separated string of all subjects in this combination
	def subjects(self):
		return ", ".join(self.subjects_list())

	def save(self, *args, **kwargs):
		self.abbreviation = self.abbreviation.upper()
		super(SubjectCombination, self).save(*args, **kwargs)
        
	class Meta:
		app_label = 'curricula'
		ordering = ['abbreviation']
		verbose_name = _('subject combination')
		verbose_name_plural = _('subjects combinations')

class Topic(models.Model):
	name = models.CharField(max_length=128)
	author = models.ForeignKey(User, editable=False)

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.lower()
		super(Topic, self).save(*args, **kwargs)

	class Meta:
		app_label = 'curricula'
		verbose_name = _('topic')
		verbose_name_plural = _('topics')

class TopicCombination(models.Model):
	combination = models.ManyToManyField(Topic)
	subject = models.ForeignKey(SubjectCombination)
	abbreviation = models.CharField(max_length=2)
	author = models.ForeignKey(User, editable=False)

	def __unicode__(self):
		return "%s - %s" % (self.abbreviation, self.topics())

	def save(self, *args, **kwargs):
		self.abbreviation = self.abbreviation.upper()
		super(TopicCombination, self).save(*args, **kwargs)

	# Returns an array of topics belonging to this combination
	def topics_list(self):
		return [x.name for x in self.combination.all()]

	# Returns a comma separated string of all topics in this combination
	def topics(self):
		return ", ".join(self.topics_list())
    
	class Meta:
		app_label = 'curricula'
		verbose_name = _('topic combination')
		verbose_name_plural = _('topics combinations')

def subjectcombination_find_by_set(subjects):
	if subjects == None:
		return None

	possible = SubjectCombination.objects.filter(combination__in=subjects)
	for p in possible:
		if set(p.combination.all()) == set(subjects):
			return p
	return None

def topiccombination_find_by_set(topics, subjectcombination):
	if subjectcombination == None or topics == None:
		return None

	possible = TopicCombination.objects.filter(combination__in=topics)
	for p in possible:
		if set(p.combination.all()) == set(topics) and p.subject == subjectcombination:
			return p
	return None

def topiccombination_find_all(topics):
	possible = TopicCombination.objects.filter(combination__in=topics)
	return [p for p in possible if set(p.combination.all()) == set(topics)]

def topiccombination_find_any(topics):
	suggestions = set([])
	for topic in topics:
		suggestions = suggestions | set([(tc.abbreviation, tc.topics()) for tc in topic.topiccombination_set.all()])

	return [{'abbreviation':a,'topics':t} for (a,t) in suggestions]

def subject_abbreviation_free(abbreviation):
	a = SubjectCombination.objects.filter(abbreviation=abbreviation.upper())
	if len(a) > 0:
		return False
	return True

def topic_abbreviation_free(abbreviation, subjectcombination):
	a = TopicCombination.objects.filter(subject=subjectcombination)
	a = a.filter(abbreviation=abbreviation.upper())
	if len(a) > 0:
		return False
	return True

class Goal(models.Model):
	goal = models.CharField(max_length=256)
	author = models.ManyToManyField(User, editable=False)

	def __unicode__(self):
		return self.goal

	class Meta:
		app_label = 'curricula'

class Evaluation(models.Model):
	goal = models.ForeignKey(Goal)
	evaluation = models.TextField()
	author = models.ManyToManyField(User, editable=False)

	def __unicode__(self):
		return self.evaluation

	class Meta:
		app_label = 'curricula'
		verbose_name = _('evaluation')
		verbose_name_plural = _('evaluations')


class Course(models.Model):
	STATUS_CHOICES = ( 
			(1, _('In progress')),
			(2, _('Ready for inspection')),
			(3, _('Approved by school')),
			(4, _('Officially approved')), 
			(5, _('Rejected by school')),
			(6, _('Rejected officially')),
			)

	LEVEL_CHOICES = (
			(1, _('Level 1')),
			(2, _('Level 2')),
			(3, _('Level 3')),
			(4, _('Level 4')),
		 	)

	descriptive_name = models.CharField(verbose_name=_('descriptive name'), max_length=255, default='', blank=True, help_text='Stutt setning sem lýsir innihaldi námskeiðsins')
# _('Write a short sentence which describes the subject and the topic of the course. Examples of descriptive names are: 21st century Icelandic art history, Maintenance control of machines, Sales and services, German pronunciation and vocabulary, Hair coloring, Linux administration.')

	subjects = models.ForeignKey(SubjectCombination, blank=True, verbose_name=_('subjects'), help_text='Grunnsvið eða fög sem eru kennd (aðgreind með kommu)')
# _('Write or choose from the list to the right a subject that describes the foundational area of expertise which is taught in the course. Examples of subjects are: Mathematics, Icelandic, chemistry, electrical circuits, first aid, media, hair styling, industrial control, machine handling, management, electrical engineering, industrial architecture. It is permissible to name more than one subjects (separated by a comma) when creating multi-disciplinary courses.')

	topics = models.ForeignKey(TopicCombination, blank=True, verbose_name=_('topics'), help_text='Helstu umfjöllunarefni (aðgreind með kommu)')
# _('Write or choose from the list to the right one to four of the most influential topics of the course. Separate the topics by a comma. Examples of topics are: Pedagogy, genetics, statistics, grammar, alternating currents, machine architecture, welding. Keep in mind that only two letters will represent the topic in the course abbreviation')

	level = models.IntegerField(_('level'), choices=LEVEL_CHOICES, default=1, help_text='Hæfniþrep sem að minnsta kosti 75% af námskeiðinu er á ')
# _("Make a suggestion about the course's competence level. Choose the corresponding competence level below. Note that at least 75%% of the course topics should belong to the course's competence level")

	credits = models.IntegerField(_('school credits'), default=0, blank=True, help_text='Hver eining samsvarar þriggja daga vinnu nemenda (6-8 klst/dag)')
# _('Here is the scope of the course given in school credits. A school credit is the measurement of an average student work contribution in school, disregarding whether the studies are practical or theoretical and whether it takes place within or outside the school. Each school credit translates to about three days of work (6-8 hours a day) for the student. It is advised to keep the competence goals in mind when estimating work contribution and assigning school credits. (To use old school credits it is necessary to configure the schools information accordingly. This system will automatically translate between the two credits systems according to the formula: school credits = old credits x 60/35.)')

	description = models.TextField(_('description'), default='', blank=True, help_text=_('A short description of the main content of the course'))

	prerequisites = models.TextField(_('prerequisites'), default='', blank=True, help_text='Lýsing á skilyrðum sem nemendur þurfa að uppfylla til að mega taka námskeiðið')
# _('Here are listed the prerequisites for the course if there are any. Prerequisites can for example be specific courses that the student must have passed before or at the same time as this course, the amount of school credits for a specific topic on a specific level or any other description of prerequisites the student must fulfill.')

	knowledge_goals = models.ManyToManyField(Goal, verbose_name=_('knowledge goals'), related_name='knowledge_goals', blank=True, null=True, help_text='2-10 atriði sem lýsa staðreyndum, lögmálum og aðferðum sem nemendur eiga að þekkja og skilja')
# _('Knowledge goals describe the knowledge the student shall have acquired by passing the course. Knowledge ranges from facts to laws to processes and is both theoretical and applicable. The course evaluation takes these goals into account. On average 2 to 10 goals are expected to be added as continuation of the following sentence: A studet shall have acquired knowledge and understanding of:')

curricula/forms/stakeholders.py
from django.forms import ModelForm, Form
from django.shortcuts import render_to_response
from django.contrib.formtools.wizard import FormWizard
from django.http import HttpResponseRedirect

from curricula.models.extra_information import Stakeholder

"""
Stakeholder form to create a new stakeholder (or update it)
"""
class StakeholderForm(ModelForm):
	class Meta:
		model = Stakeholder

templates/menntagatt/curricula/approve_course.html
{% extends "contentbox.html" %}
{% load markup %}
{% load i18n %}
{% block content %}

<h1>{{course.descriptive_name}} - {{course.id_name}}</h1>

<form action="." method="POST">{% csrf_token %}
<input type="hidden" name="unique-id" value="{{course.unique_id}}">
<label>{% trans "Are you sure you want to approve this course on behalf of the school?" %}</label>
<input type="submit" name="approve" value="{% trans 'Yes, I am sure' %}"> <input type="submit" name="not-approved" value="{% trans 'No, I reject this course' %}">
</form>

{% include "curricula/course_info.html" %}

{% endblock %}

templates/menntagatt/curricula/course.html
{% extends "contentbox.html" %}
{% load markup %}
{% block content %}
<h1>{{course.descriptive_name}} - {{course.id_name}}</h1>
{{course.get_status_display}}

{% include "curricula/course_info.html" %}

{% endblock %}

templates/menntagatt/curricula/course_info.html
{% load markup %}
{% load i18n %}
<p>
<div><label>{% trans "Subjects" %}</label> {{course.subjects.subjects}}</div>
<div><label>{% trans "Topics" %}</label> {{course.topics.topics}}</div>
</p>

<p>
<div><label>{% trans "Level" %}</label> <p>{{course.level}}. þrep</p></div>
<div><label>{% trans "Credits" %}</label> <p>{{course.credits}} {% trans "school credits" %}</p></div>
</p>

<p>
<div><label>{% trans "Prerequisites" %}</label> {{course.prerequisites|markdown}}</div>
<div><label>{% trans "Description" %}</label> {{course.description|markdown}}</div>
</p>

<p>
<label>{% trans "Knowledge goals" %}</label>
<ul>{% for goal in course.knowledge_goals.all %}
<li>{{goal|markdown}}</li>
{% endfor %}</ul>

<label>{% trans "Skill goals" %}</label>
<ul>{% for goal in course.skills_goals.all %}
<li>{{goal|markdown}}</li>
{% endfor %}</ul>

<label>{% trans "Competence goals" %}</label>
<ul>{% for goal in course.competence_goals.all %}
<li>{{goal|markdown}}
<ul>{% for evaluation in goal.evaluation_set.all %}
<li>{{ evaluation|markdown }}</li>
{% endfor %}</ul></li>
{% endfor %}</ul>
</p>

<p>
{% if course.evaluation %}<div><label>{% trans "Additional evaluation" %}</label> {{course.evaluation|markdown}}</div>{% endif %}
</p>

templates/menntagatt/curricula/delete_course.html
{% extends "contentbox.html" %}
{% load markup %}
{% load i18n %}
{% block content %}

<h1>{{course.descriptive_name}} - {{course.id_name}}</h1>

<form action="." method="POST">{% csrf_token %}
<input type="hidden" name="unique-id" value="{{course.unique_id}}">
<label>{% trans "Are you sure you want to delete this course?" %}</label>
<input type="submit" value="{% trans 'Yes, I am sure' %}">
</form>

{% include "curricula/course_info.html" %}

{% endblock %}

templates/menntagatt/curricula/make_course_exemplary.html
{% extends "contentbox.html" %}
{% load markup %}
{% load i18n %}

{% block stylesheet %}
    <link rel="stylesheet" href="/media/css/builder.css"/> 
{% endblock %}

{% block content %}

<h1>{{course.descriptive_name}} - {{course.id_name}}</h1>

<form action="." method="POST">{% csrf_token %}

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Descriptive name" %}</label>
    {{course.descriptive_name}}
    <label>{% trans "Subjects" %}</label>
    {{course.subjects.subjects}}
    <label>{% trans "Topics" %}</label>
    {{course.topics.topics}}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the descriptive name, the subjects and the topics" %}</label>
    <textarea name="name_subjects_and_topics"></textarea>
  </div>
</div>

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Description" %}</label>
    {{course.description}}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the description" %}</label>
    <textarea name="description"></textarea>
  </div>
</div>

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Prerequisites" %}</label>
    {{course.prerequisites}}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the prerequisites" %}</label>
    <textarea name="prerequisites"></textarea>
  </div>
</div>

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Level" %}</label>
    {{course.get_level_display}}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the level" %}</label>
    <textarea name="level"></textarea>
  </div>
</div>

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Knowledge goals" %}</label>
    <ul>{% for goal in course.knowledge_goals.all %}
      <li>{{goal}}</li>
    {% endfor %}</ul>
    <label>{% trans "Skill goals" %}</label>
    <ul>{% for goal in course.skills_goals.all %}
      <li>{{goal}}</li>
    {% endfor %}</ul>
    <label>{% trans "Competence goals" %}</label>
    <ul>{% for goal in course.competence_goals.all %}
      <li>{{goal}}{% if goal.evaluation_set.all|length > 0 %}<br/>
	<strong>{% trans "Evaluation" %}</strong><ul>{% for evaluation in goal.evaluation_set.all %}
	  <li>{{evaluation}}</li>
	  {% endfor %}</ul>{% endif %}
      </li>
    {% endfor %}</ul>
    <label>{% trans "Credits" %}</label>
    {{course.credits}} {% trans "School credits" %}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the knowledge, skill, and competence goals" %}</label>
    <textarea name="goals"></textarea>
    <label>{% trans "Notes about" %} {% trans "the evaluation of competence goals" %}</label>
    <textarea name="competence_evaluation"></textarea>
    <label>{% trans "Notes about" %} {% trans "the credits estimation based on the competence goals" %}</label>
    <textarea name="competence_goals_and_credits"></textarea>
  </div>
</div>

<div class="exemplary-container">
  <div class="course-information">
    <label>{% trans "Evaluation" %}</label>
    {{course.evaluation}}
  </div>
  <div class="exemplary-input">
    <label>{% trans "Notes about" %} {% trans "the evaluation" %}</label>
    <textarea name="evaluation"></textarea>
  </div>
</div>

<input type="hidden" name="course" value="{{course.id}}">
<input type="submit" value="{% trans 'Create exemplary course' %}">
</form>
{% endblock %}

templates/menntagatt/curricula/profession_list.html
{% extends "contentbox.html" %}
{% load i18n %}
{% block stylesheet %}
    <link rel="stylesheet" href="/media/css/builder.css"/>
{% endblock %}

{% block content %}
<div id="content">
<h1>Námslok</h1>

{% for p in professions %}
<h3>{{p.title|capfirst}}</h3>
<em>{{p.exam}} - {{p.field.title}}</em>
<p>
{{p.description}}
</p>
{% endfor %}

</div>
{% endblock %}

templates/menntagatt/curricula/stakeholder.html
{% extends "contentbox.html" %}
{% load i18n %}
{% block content %}
<h1>{{stakeholder.name}}</h1>

<p>{{stakeholder.address}}<br/>
{{stakeholder.municipality}}</p>

<p>{{stakeholder.telephone}}<br/>
{{stakeholder.email}}<br/>
{{stakeholder.fax}}</p>

<p><a href="{{stakeholder.website}}">{{stakeholder.website}}</a></p>

<h2>{% trans "Interested in" %}:</h2>
<ul>{% for field in stakeholder.fields.all %}
<li>{{field}}</li>
{% endfor %}</ul>

{% endblock %}

templates/menntagatt/curricula/view_exemplary_course.html
{% extends "contentbox.html" %}
{% load markup %}
{% load i18n %}

{% block stylesheet %}
    <link rel="stylesheet" href="/media/css/builder.css"/> 
{% endblock %}

{% block content %}

<h1>{% trans "The exemplary course" %}: {{exemplary.course.descriptive_name}} - {{exemplary.course.id_name}}</h1>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.name_subjects_and_topics %} no-exemplary-notes{% endif %}">
    <label>{% trans "Descriptive name" %}</label>
    {{exemplary.course.descriptive_name}}
    <label>{% trans "Subjects" %}</label>
    {{exemplary.course.subjects.subjects}}
    <label>{% trans "Topics" %}</label>
    {{exemplary.course.topics.topics}}
  </div>
  {% if exemplary.name_subjects_and_topics %}
  <div class="exemplary-input">
    <label>{% trans "Notes about the descriptive name, the subjects and the topics" %}</label>
    <p>{{exemplary.name_subjects_and_topics}}</p>
  </div>
  {% endif %}
</div>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.description %} no-exemplary-notes{% endif %}">
    <label>{% trans "Description" %}</label>
    {{exemplary.course.description}}
  </div>
  {% if exemplary.description %}
  <div class="exemplary-input">
    <label>{% trans "Notes about the description" %}</label>
    <p>{{exemplary.description}}</p>
  </div>
  {% endif %}
</div>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.prerequisites %} no-exemplary-notes{% endif %}">
    <label>{% trans "Prerequisites" %}</label>
    {{exemplary.course.prerequisites}}
  </div>
  {% if exemplary.prerequisites %}
  <div class="exemplary-input">
    <label>{% trans "Notes about the prerequisites" %}</label>
    <p>{{exemplary.prerequisites}}</p>
  </div>
  {% endif %}
</div>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.level %} no-exemplary-notes{% endif %}">
    <label>{% trans "Level" %}</label>
    {{exemplary.course.get_level_display}}
  </div>
  {% if exemplary.level %}
  <div class="exemplary-input">
    <label>{% trans "Notes about the level" %}</label>
    <p>{{exemplary.level}}</p>
  </div>
  {% endif %}
</div>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.goals and not exemplary.competence_evaluation and not exemplary.comptence_goals_and_credits %} no-exemplary-notes{% endif %}">
    <label>{% trans "Knowledge goals" %}</label>
    <ul>{% for goal in exemplary.course.knowledge_goals.all %}
      <li>{{goal}}</li>
    {% endfor %}</ul>
    <label>{% trans "Skill goals" %}</label>
    <ul>{% for goal in exemplary.course.skills_goals.all %}
      <li>{{goal}}</li>
    {% endfor %}</ul>
    <label>{% trans "Competence goals" %}</label>
    <ul>{% for goal in exemplary.course.competence_goals.all %}
      <li>{{goal}}{% if goal.evaluation_set.all|length > 0 %}<br/>
	<strong>{% trans "Evaluation" %}</strong><ul>{% for evaluation in goal.evaluation_set.all %}
	  <li>{{evaluation}}</li>
	  {% endfor %}</ul>{% endif %}
      </li>
    {% endfor %}</ul>
    <label>{% trans "Credits" %}</label>
    {{exemplary.course.credits}} {% trans "School credits" %}
  </div>
  {% if exemplary.goals or exemplary.competence_evaluation or exemplary.comptence_goals_and_credits %}
  <div class="exemplary-input">
    {% if exemplary.goals %}
    <label>{% trans "Notes about the knowledge, skill, and competence goals" %}</label>
    <p>{{exemplary.goals}}</p>
    {% endif %}
    {% if exemplary.competence_evaluation %}
    <label>{% trans "Notes about the evaluation of competence goals" %}</label>
    <p>{{exemplary.competence_evaluation}}</p>
    {% endif %}
    {% if exemplary.competence_goals_and_credits %}
    <label>{% trans "Notes about the credits estimation based on the competence goals" %}</label>
    <p>{{exemplary.competence_goals_and_credits}}</p>
    {% endif %}
  </div>
  {% endif %}
</div>

<div class="exemplary-container">
  <div class="course-information{% if not exemplary.evaluation %} no-exemplary-notes{% endif %}">
    <label>{% trans "Evaluation" %}</label>
    {{exemplary.course.evaluation}}
  </div>
  {% if exemplary.evaluation %}
  <div class="exemplary-input">
    <label>{% trans "Notes about the evaluation" %}</label>
    <p>{{exemplary.evaluation}}</p>
  </div>
  {% endif %}
</div>
{% endblock %}